### ISSUE TITLE
[Feature Request] Kettle checking for hot blocks instead of simply checking furnace

### ISSUE THREAD

**Issue by NightmareTwilight** [a-soulspark/TeaKettle#5]
Essentially the title, from what I see of your code, you're not checking if the block is a "hot" block (exists functionality for this in base forge), but rather specific block types.

**Comment by a-soulspark** [comment]
> (exists functionality for this in base forge)

Is there? I thought a "hot" block was somewhat abstract, and I couldn't find any way to check for that.
If there _is_ a way to do that, please tell me! I'd love to add that to the mod!

**Comment by NightmareTwilight** [comment]
Seems I was wrong, though I could have sworn that it existed, guess I'll just have to ask for forge to add it.

**Comment by NightmareTwilight** [comment]
I have now made a suggestion on forge to add a standardized "Hot Block" block tag.

**Comment by a-soulspark** [comment]
Thanks for the effort! For now, you can change the block tag `tea_kettle:hot` if you want to change what blocks are considered hot.
A global datapack in a modpack should do the trick (CraftTweaker was supposed to work but someone has had issues with it)

The `tea_kettle:furnaces` tag also describes blocks that aren't `instanceof AbstractFurnaceBlock` but are only hot when their "lit" blockstate is true (if the former isn't the case, the code already deals with it. that's why vanilla furnaces aren't included in the tag)
I used it for the Iron Furnaces mod, for example, so those furnaces are only hot when they're burning something.
